AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/*'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'spec/factories/**/*'
    - 'spec/jobs/*'
    - 'spec/lib/*'
    - 'config/environments/*'

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30

Metrics/AbcSize:
  Max: 35
