# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  s3_region: <%= ENV["S3_REGION"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key_secret: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  ldap_server: <%= ENV["LDAP_SERVER"] %>
  ldap_server_port: <%= ENV["LDAP_SERVER_PORT"] %>
  ldap_server_username: <%= ENV["LDAP_SERVER_USERNAME"] %>
  ldap_server_password: <%= ENV["LDAP_SERVER_PASSWORD"] %>
  kairos_app_id: <%= ENV["KAIROS_APP_ID"] %>
  kairos_app_key: <%= ENV["KAIROS_APP_KEY"] %>

development:
  <<: *default

test:
  secret_key_base: a714d687e4a236ad75a0739e9bb585359d4e2616537f56ee657ad70e9b512a97ba44a774b9d705fdb8cbc857d04cf96a45f6fca063f54d387374eb584cfbc52b
  domain_name: 127.0.0.1:3000
  s3_region: us-east-1
  s3_bucket_name: kontaktliste
  ldap_server: <%= ENV["LDAP_SERVER"] %>
  ldap_server_port: <%= ENV["LDAP_SERVER_PORT"] %>
  ldap_server_username: <%= ENV["LDAP_SERVER_USERNAME"] %>
  ldap_server_password: <%= ENV["LDAP_SERVER_PASSWORD"] %>
  kairos_app_id: <%= ENV["KAIROS_APP_ID"] %>
  kairos_app_key: <%= ENV["KAIROS_APP_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
