# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d79f14924e443c37b2046e2b08705f3d78cfabc0c2610b2272ca742d7bae11863b1e781fc5f75bd69a1a8e7dd03110668f2756c7beffb7fb4d806cd2abfc78
  domain_name: 127.0.0.1:3000
  s3_region: us-east-1
  s3_bucket_name: kontaktliste
  aws_access_key_id: AKIAJKXCR5ZIPG6YTC3A
  aws_access_key_secret: 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

test:
  secret_key_base: a714d687e4a236ad75a0739e9bb585359d4e2616537f56ee657ad70e9b512a97ba44a774b9d705fdb8cbc857d04cf96a45f6fca063f54d387374eb584cfbc52b
  domain_name: 127.0.0.1:3000
  s3_region: us-east-1
  s3_bucket_name: kontaktliste
  aws_access_key_id:
  aws_access_key_secret:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["DOMAIN_NAME"] %>
  s3_region: <%= ENV["S3_REGION"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_access_key_secret: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
